//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIST_REVIEW
    {
        public int ARTIST_ID { get; set; }
        public System.DateTime ARTIST_REVIEW_DATE_TIME { get; set; }
        public short ARTIST_REVIEW_RATING { get; set; }
        public string ARTIST_REVIEW_BODY { get; set; }
        public bool ARTIST_REVIEW_VERIFIED { get; set; }
        public int CUSTOMER_ID { get; set; }
    
        public ARTIST ARTIST { get; set; }
        public CUSTOMER CUSTOMER { get; set; }
    }
}
