//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConn : DbContext
    {
        public DBConn()
            : base("name=DBConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ARTIST> ARTISTs { get; set; }
        public virtual DbSet<ARTIST_REVIEW> ARTIST_REVIEW { get; set; }
        public virtual DbSet<ARTIST_TYPE> ARTIST_TYPE { get; set; }
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<CHILD_EVENT> CHILD_EVENT { get; set; }
        public virtual DbSet<CONTRACT> CONTRACTS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EVENT_REVIEW> EVENT_REVIEW { get; set; }
        public virtual DbSet<GUEST_BOOKING> GUEST_BOOKING { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PARENT_EVENT> PARENT_EVENT { get; set; }
        public virtual DbSet<SOCIAL_MEDIA> SOCIAL_MEDIA { get; set; }
        public virtual DbSet<TICKET> TICKETs { get; set; }
        public virtual DbSet<VENUE> VENUEs { get; set; }
        public virtual DbSet<VENUE_REVIEW> VENUE_REVIEW { get; set; }
    }
}
