//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_REVIEW
    {
        public int PARENT_EVENT_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public System.DateTime EVENT_REVIEW_DATE_TIME { get; set; }
        public short EVENT_REVIEW_RATING { get; set; }
        public string EVENT_REVIEW_BODY { get; set; }
        public bool EVENT_REVIEW_VERIFIED { get; set; }
    
        public CUSTOMER CUSTOMER { get; set; }
        public  PARENT_EVENT PARENT_EVENT { get; set; }
    }
}
