//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUEST_BOOKING
    {
        public int GUEST_BOOKING_ID { get; set; }
        public int TICKET_ID { get; set; }
        public string GUEST_EMAIL { get; set; }
        public string GUEST_ADDRESS { get; set; }
        public string GUEST_POSTCODE { get; set; }
        public int GUEST_BOOKING_QUANTITY { get; set; }
        public System.DateTime GUEST_BOOKING_DATE_TIME { get; set; }
    
        public  TICKET TICKET { get; set; }
    }
}
