//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENT_EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARENT_EVENT()
        {
            this.CHILD_EVENT = new HashSet<CHILD_EVENT>();
            this.EVENT_REVIEW = new HashSet<EVENT_REVIEW>();
        }
    
        public int PARENT_EVENT_ID { get; set; }
        public int SOCIAL_MEDIA_ID { get; set; }
        public string PARENT_EVENT_NAME { get; set; }
        public string PARENT_EVENT_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public 
            
            ICollection<CHILD_EVENT> CHILD_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<EVENT_REVIEW> EVENT_REVIEW { get; set; }
        public  SOCIAL_MEDIA SOCIAL_MEDIA { get; set; }
    }
}
