//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.GUEST_BOOKING = new HashSet<GUEST_BOOKING>();
        }
    
        public int TICKET_ID { get; set; }
        public decimal TICKET_PRICE { get; set; }
        public string TICKET_DESCRIPTION { get; set; }
        public int TICKET_AMOUNT_REMAINING { get; set; }
        public string TICKET_TYPE { get; set; }
        public int CHILDEVENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<BOOKING> BOOKINGs { get; set; }
        public  CHILD_EVENT CHILD_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<GUEST_BOOKING> GUEST_BOOKING { get; set; }
    }
}
