//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENUE()
        {
            this.CHILD_EVENT = new HashSet<CHILD_EVENT>();
            this.VENUE_REVIEW = new HashSet<VENUE_REVIEW>();
        }
    
        public int VENUE_ID { get; set; }
        public int SOCIAL_MEDIA_ID { get; set; }
        public string VENUE_DESCRIPTION { get; set; }
        public short VENUE_CAPACITY_SEATING { get; set; }
        public short VENUE_CAPACITY_STANDING { get; set; }
        public bool VENUE_DISABLED_ACCESS { get; set; }
        public string VENUE_FACILITES { get; set; }
        public int VENUE_PARKING { get; set; }
        public string VENUE_PHONE_NUMBER { get; set; }
        public string VENUE_EMAIL { get; set; }
        public string VENUE_ADDRESS { get; set; }
        public string VENUE_POSTCODE { get; set; }
        public string VENUE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<CHILD_EVENT> CHILD_EVENT { get; set; }
        public  SOCIAL_MEDIA SOCIAL_MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<VENUE_REVIEW> VENUE_REVIEW { get; set; }
    }
}
